INSERT INTO CATEGORY (name, creation_date) VALUES ('Abonnements', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Activités', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Alimentation', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Argent de Poche', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Autre', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Boisson', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Cinema', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Coiffeur', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Courses', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Divertissement', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Epargne', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Facture', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Fast-Food', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Formation', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Fournitures', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Inconnue', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Logement', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Loyer', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Médical', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Parking', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Plein', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Remboursement', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Cadeaux', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Restes', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Resto', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Retrait', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Salaire', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Transfert', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Transports', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('Vêtements', TO_DATE('10/10/20','dd/MM/yy'));

commit;