CREATE TABLE category (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name NVARCHAR2(100) NOT NULL,
    creation_date DATE NOT NULL,
    CONSTRAINT category_pk PRIMARY KEY (id)
);

INSERT INTO CATEGORY (name, creation_date) VALUES ('category_name_1', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('category_name_2', TO_DATE('12/11/20','dd/MM/yy'));

CREATE TABLE organisation (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name NVARCHAR2(100) NOT NULL,
    address NVARCHAR2(500) NOT NULL,
    CONSTRAINT organisation_pk PRIMARY KEY (id)
);

INSERT INTO ORGANISATION (name, address) VALUES ('organisation_name_1', 'organisation_address_1');
INSERT INTO ORGANISATION (name, address) VALUES ('organisation_name_2', 'organisation_address_2');

CREATE TABLE source (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name NVARCHAR2(100) NOT NULL,
    creation_date DATE NOT NULL,
    organisation_id NUMBER(10),
    CONSTRAINT source_pk PRIMARY KEY (id),
    CONSTRAINT source_organisation_fk
        FOREIGN KEY (organisation_id)
            REFERENCES organisation(id)
                ON DELETE SET NULL
);

INSERT INTO SOURCE (name, creation_date, organisation_id) VALUES ('source_name_1', TO_DATE('10/10/20','dd/MM/yy'), 1);
INSERT INTO SOURCE (name, creation_date, organisation_id) VALUES ('source_name_2', TO_DATE('12/11/20','dd/MM/yy'), 2);

CREATE TABLE Record (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pay_date DATE NOT NULL,
    amount NUMBER(6,2) NOT NULL,
    category_id NUMBER(10),
    source_id NUMBER(10),
    comments NVARCHAR2(500),
    CONSTRAINT record_pk PRIMARY KEY (id),
    CONSTRAINT record_category_fk
        FOREIGN KEY (category_id)
            REFERENCES category(id)
            ON DELETE SET NULL,
    CONSTRAINT record_source_fk
        FOREIGN KEY (source_id)
            REFERENCES source(id)
            ON DELETE SET NULL
);

INSERT INTO RECORD (pay_date, amount, category_id, source_id, comments)
VALUES (TO_DATE('10/10/20','dd/MM/yy'), 10.01, 1, 1, 'record_comments_1');
INSERT INTO RECORD (pay_date, amount, category_id, source_id, comments)
VALUES (TO_DATE('12/11/20','dd/MM/yy'), 20, 2, 2, 'record_comments_2');

commit;