CREATE TABLE record (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pay_date DATE NOT NULL,
    amount NUMBER(6,2) NOT NULL,
    category_id NUMBER(10) NOT NULL,
    source_id NUMBER(10) NOT NULL,
    comments NVARCHAR2(500),
    CONSTRAINT record_pk PRIMARY KEY (id),
    CONSTRAINT record_category_fk
        FOREIGN KEY (category_id)
            REFERENCES category(id),
    CONSTRAINT record_source_fk
        FOREIGN KEY (source_id)
            REFERENCES source(id)
);

INSERT INTO RECORD (pay_date, amount, category_id, source_id, comments)
VALUES (TO_DATE('10/10/20','dd/MM/yy'), 10.01, 1, 1, 'record_comments_1');
INSERT INTO RECORD (pay_date, amount, category_id, source_id, comments)
VALUES (TO_DATE('12/11/20','dd/MM/yy'), 20, 2, 2, 'record_comments_2');

commit;