CREATE TABLE source (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name NVARCHAR2(100) NOT NULL,
    creation_date DATE NOT NULL,
    organisation_id NUMBER(10),
    CONSTRAINT source_pk PRIMARY KEY (id),
    CONSTRAINT source_organisation_fk
        FOREIGN KEY (organisation_id)
            REFERENCES organisation(id)
);

INSERT INTO SOURCE (name, creation_date, organisation_id) VALUES ('source_name_1', TO_DATE('10/10/20','dd/MM/yy'), 1);
INSERT INTO SOURCE (name, creation_date, organisation_id) VALUES ('source_name_2', TO_DATE('12/11/20','dd/MM/yy'), 2);
commit;