CREATE TABLE organisation (
  id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name NVARCHAR2(100) NOT NULL,
  address NVARCHAR2(500) NOT NULL,
  CONSTRAINT organisation_pk PRIMARY KEY (id)
);

INSERT INTO ORGANISATION (name, address) VALUES ('organisation_name_1', 'organisation_address_1');
INSERT INTO ORGANISATION (name, address) VALUES ('organisation_name_2', 'organisation_address_2');

commit;