CREATE TABLE category (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name NVARCHAR2(100) NOT NULL,
    creation_date DATE NOT NULL,
    CONSTRAINT category_pk PRIMARY KEY (id)
);

INSERT INTO CATEGORY (name, creation_date) VALUES ('category_name_1', TO_DATE('10/10/20','dd/MM/yy'));
INSERT INTO CATEGORY (name, creation_date) VALUES ('category_name_2', TO_DATE('12/11/20','dd/MM/yy'));

commit;